# GitHub Pages config
include:
  - .htaccess
  - robots.txt
  - sitemap.xml

# Serve JSON with correct content type
defaults:
  - scope:
      path: "*.json"
    values:
      content_type: "application/json"
